src/Entity/Animal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnimalRepository")
 */
class Animal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=50)
     */
    private $nome; 
    
     /**
     * @var date
     * @ORM\Column(type="date")
     */
    private $data_nascimento; 


    /**     
     * @var object
     * @ORM\ManyToMany(targetEntity="App\Entity\Cliente", mappedBy="animal")
     */
    private $cliente; 


    /**
     * @var object
     * @ORM\ManyToOne(targetEntity="App\Entity\Raca", inversedBy="id")     
     */
    private $raca;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the value of nome
     *
     * @return  string
     */ 
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Set the value of nome
     *
     * @param  string  $nome
     *
     * @return  self
     */ 
    public function setNome(string $nome)
    {
        $this->nome = $nome;

        return $this;
    }

    /**
     * Get the value of data_nascimento
     *
     * @return  date
     */ 
    public function getDataNascimento()
    {
        return $this->data_nascimento;
    }

    /**
     * Set the value of data_nascimento
     *
     * @param  date  $data_nascimento
     *
     * @return  self
     */ 
    public function setDataNascimento($data_nascimento)
    {
        $this->data_nascimento = $data_nascimento;

        return $this;
    }

    /**
     * Get the value of cliente
     *
     * @return  object
     */ 
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * Set the value of cliente
     *
     * @param  object  $cliente
     *
     * @return  self
     */ 
    public function setCliente(object $cliente)
    {
        $this->cliente = $cliente;

        return $this;
    }

   
    /**
     * Get the value of raca
     *
     * @return  object
     */ 
    public function getRaca()
    {
        return $this->raca;
    }

    /**
     * Set the value of raca
     *
     * @param  object  $raca
     *
     * @return  self
     */ 
    public function setRaca(object $raca)
    {
        $this->raca = $raca;

        return $this;
    }
}

src/Controller/AnimaisController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\VarDumper\VarDumper;

class AnimaisController extends AbstractController
{

    /**
     * @Route("/animais", name="listar_animais")
     * @Template("animais/index.html.twig")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager(); 
        $animais = $em->getRepository(Animal::class)->findAll();
        return ['animais' => $animais];         
    }


    /**
     * @Route("/animal/visualizar/{id}", name="visualizar_animal")
     * @Template("animais/view.html.twig")
     * 
     * @param Animal $animal
     * @return array
     */
    public function view(Animal $animal)
    {        
        return ['animal' => $animal]; 
    }


    /**
     * @Route("animal/cadastrar", name="cadastrar_animal")
     * @Template("animais/create.html.twig")
     */    
    public function create(Request $request)
    {
        $animal = new Animal(); 
        $form = $this->createForm(AnimalType::class, $animal); 
        $form->handleRequest($request); 

        if($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager(); 
            $em->persist($animal); 
            $em->flush(); 

            $this->addFlash('success', "Animal foi salvo com sucesso!"); 
            return $this->redirectToRoute('visualizar_animal', [
                'id' => $animal->getId()
            ]); 
        }

        return [
            'form' => $form->createView()
        ];
    }

}

templates/animais/create.html.twig
{% extends "base.html.twig" %}

{% block title %} Cadastrar Animal {% endblock %}

{% block body %}   

<h1>Cadastrar Animal</h1>
<hr>
{{ form(form) }}

{% endblock %}

templates/animais/index.html.twig
{% extends "base.html.twig" %}

{% block title %} Listagem de Animais {% endblock %}
{% block body %}
    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}        
    {% for flashMessage in app.session.flashbag.get('warning') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}        
    {% for flashMessage in app.session.flashbag.get('danger') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}        
    <h1>Listagem de Animais</h1>
    <hr>
    <div class="row">
        <div class="md-12">
            <a href="{{ path('cadastrar_animal') }}" class="btn btn-primary pull-right">Cadastrar Animal</a>
        </div>
    </div>
    <table class="table table-hover table-striped mt-3">
        <thead>
            <tr>
                <th>Cod.</th>
                <th>Animal</th>
                <th>Data Nasc</th>
            </tr>
        </thead>
        <tbody>
            {% for animal in animais %}
            <tr>
                <td>{{ animal.id }}</td>
                <td><a href="{{ path('visualizar_animal', {'id': animal.id}) }}">{{ animal.nome }}</a></td>
                <td>{{ animal.dataNascimento | date('d/m/Y') }}</td>
            </tr>
            {% else %}
                <tr>
                <td colspan="3">Nenhum registro encontrado!</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/animais/view.html.twig
{% extends "base.html.twig" %}

{% block title %} {{ animal.nome }} - Visualização de Animal {% endblock %}

{% block body %}   

<h1>Visualizando animal - {{ animal.nome }}</h1>
<table class="table table-striped">
    <tr><th colspan="2">Dados do Animal</th></tr>
    <tr>
        <th>Cod</th>
        <th>{{ animal.id }}</th>
    </tr>
    <tr>
        <th>Nome</th>
        <th>{{ animal.nome }}</th>
    </tr>
    <tr>
        <th>Data de Nascimento</th>
        <th>{{ animal.dataNascimento | date('d/m/Y')}}</th>
    </tr>    

    <tr colspan="2"><th colspan="2">Detalhes do Animal</th></tr>
    <tr>
        <th>Raça</th>
        <th>{{ animal.raca.nome }}</th>
    </tr>
    <tr>
        <th>Espécie</th>
        <th>{{ animal.raca.especie.nome }}</th>
    </tr>
    <tr colspan="2"><th colspan="2">Proprietários</th></tr>
    <tr>
        <th></th>
        <th>
        <ul>
        {% for cliente in animal.cliente %}
            <li><a href="{{ path('visualizar_cliente', { 'id': cliente.id }) }}">{{ cliente.nome }}</a></li>
        {% else %}
            <li>Este animal não tem nenhum proprietário, quer adotá-lo?</li>
        {% endfor %}
        </ul>
        </th>
    </tr>


</table>

{% endblock %}